remove indirection when initializing config file
note that the comment about importing views before models (and now
challenge) is to avoid the following exception:

    ImportError: cannot import name 'db' from partially initialized
      module 'serles.models' (most likely due to a circular import)